name: Release

on:
  push:
    branches: [master]
    paths:
      - "**/*.go"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for semantic-release to analyze commit history

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.26"

      - name: Create .env file
        run: |
          echo "SERVICE_NAME=core_service" >> .env
          echo "HTTP_PORT=:5005" >> .env
          echo "HTTP_DEVELOPMENT=true" >> .env
          echo "HTTP_BASE_PATH=/api/v1" >> .env
          echo "HTTP_AUTH_PATH=/api/v1/auth" >> .env
          echo "HTTP_CAMPAIGNS_PATH=/api/v1/campaigns" >> .env
          echo "HTTP_CONTACTS_PATH=/api/v1/contacts" >> .env
          echo "HTTP_CAMPAIGNSCONTACTS_PATH=/api/v1/campaigns/:campaign_id/contacts" >> .env
          echo "HTTP_CAMPAIGNMESSAGE_PATH=/api/v1/campaigns/:campaign_id/contacts/:contact_id/messages" >> .env
          echo "HTTP_SUBSCRIPTIONS_PATH=/api/v1/subscriptions" >> .env
          echo "HTTP_DEBUG_HEADERS=false" >> .env
          echo "HTTP_CLIENT_DEBUG=false" >> .env
          echo "HTTP_DEBUG_ERRORS_RESPONSE=true" >> .env
          echo "HTTP_IGNORE_LOG_URLS=metrics" >> .env
          echo "PROBES_READINESS_PATH=/ready" >> .env
          echo "PROBES_LIVENESS_PATH=/live" >> .env
          echo "PROBES_PORT=:3005" >> .env
          echo "PROBES_PPROF=:6005" >> .env
          echo "PROBES_PROMETHEUS_PATH=/metrics" >> .env
          echo "PROBES_PROMETHEUS_PORT=:8005" >> .env
          echo "PROBES_CHECK_INTERVAL_SECONDS=10" >> .env
          echo "LOGGER_LEVEL=debug" >> .env
          echo "LOGGER_DEV_MODE=false" >> .env
          echo "LOGGER_ENCODER=json" >> .env
          echo "POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}" >> .env
          echo "POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}" >> .env
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "POSTGRES_DB_NAME=${{ secrets.POSTGRES_DB_NAME }}" >> .env
          echo "POSTGRES_SSL_MODE=${{ secrets.POSTGRES_SSL_MODE }}" >> .env
          echo "REDIS_ADDR=${{ secrets.REDIS_ADDR }}" >> .env
          echo "REDIS_USERNAME=${{ secrets.REDIS_USERNAME }}" >> .env
          echo "REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}" >> .env
          echo "REDIS_DB=${{ secrets.REDIS_DB }}" >> .env
          echo "REDIS_POOL_SIZE=${{ secrets.REDIS_POOL_SIZE }}" >> .env
          echo "JAEGER_ENABLE=${{ secrets.JAEGER_ENABLE }}" >> .env
          echo "JAEGER_SERVICE_NAME=${{ secrets.JAEGER_SERVICE_NAME }}" >> .env
          echo "JAEGER_HOST_PORT=${{ secrets.JAEGER_HOST_PORT }}" >> .env
          echo "JAEGER_LOG_SPANS=${{ secrets.JAEGER_LOG_SPANS }}" >> .env
          echo "SERVER_JWT_EXPIRATION=${{ secrets.SERVER_JWT_EXPIRATION }}" >> .env

          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env
          echo "GOOGLE_REDIRECT_URL=${{ secrets.GOOGLE_REDIRECT_URL }}" >> .env

          echo "MICROSOFT_CLIENT_ID=${{ secrets.MICROSOFT_CLIENT_ID }}" >> .env
          echo "MICROSOFT_CLIENT_SECRET=${{ secrets.MICROSOFT_CLIENT_SECRET }}" >> .env
          echo "MICROSOFT_REDIRECT_URL=${{ secrets.MICROSOFT_REDIRECT_URL }}" >> .env

          echo "FACEBOOK_CLIENT_ID=${{ secrets.FACEBOOK_CLIENT_ID }}" >> .env
          echo "FACEBOOK_CLIENT_SECRET=${{ secrets.FACEBOOK_CLIENT_SECRET }}" >> .env
          echo "FACEBOOK_REDIRECT_URL=${{ secrets.FACEBOOK_REDIRECT_URL }}" >> .env

          echo "ANTHROPIC_API_KEY=${{ secrets.ANTHROPIC_API_KEY }}" >> .env
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
          echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" >> .env
          echo "DEEPSEEK_API_KEY=${{ secrets.DEEPSEEK_API_KEY }}" >> .env
          echo "QWEN_API_KEY=${{ secrets.QWEN_API_KEY }}" >> .env

      - name: Build Go application
        run: go build -o main core-service/cmd/main.go

      - name: Get version
        id: get-version
        run: |
          echo "VERSION=$(git describe --tags --always)" >> $GITHUB_OUTPUT

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: go-binary-${{ steps.get-version.outputs.VERSION }}
          path: main
          retention-days: 5

      - name: Archive Release
        run: |
          mkdir -p release
          cp main release/main-${{ steps.get-version.outputs.VERSION }}
          tar -czvf release-${{ steps.get-version.outputs.VERSION }}.tar.gz release/

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install semantic-release
        run: npm install semantic-release @semantic-release/git @semantic-release/github @semantic-release/exec --save-dev

      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
